"""Identity domain and registration use cases."""

from cadmus.identity.application import (
    ActivationError,
    ActivationFailure,
    AuthenticationError,
    AuthenticationFailure,
    AuthenticationService,
    DuplicateEmailError,
    LoginResult,
    PasswordResetError,
    PasswordResetFailure,
    PasswordResetService,
    PasswordResetValidationError,
    RegistrationService,
    RegistrationValidationError,
)
from cadmus.identity.domain import (
    AccountStatus,
    AuthenticatedSession,
    PasswordResetToken,
    User,
    VerificationToken,
)
from cadmus.identity.ports import (
    EmailSender,
    IdentityRepository,
    IdentityUnitOfWork,
    IdentityUnitOfWorkFactory,
    PasswordHasher,
    PasswordResetTokenProvider,
    SessionTokenProvider,
    VerificationTokenProvider,
)

__all__ = [
    "AccountStatus",
    "ActivationError",
    "ActivationFailure",
    "AuthenticatedSession",
    "AuthenticationError",
    "AuthenticationFailure",
    "AuthenticationService",
    "DuplicateEmailError",
    "EmailSender",
    "IdentityRepository",
    "IdentityUnitOfWork",
    "IdentityUnitOfWorkFactory",
    "LoginResult",
    "PasswordHasher",
    "PasswordResetError",
    "PasswordResetFailure",
    "PasswordResetService",
    "PasswordResetToken",
    "PasswordResetTokenProvider",
    "PasswordResetValidationError",
    "RegistrationService",
    "RegistrationValidationError",
    "SessionTokenProvider",
    "User",
    "VerificationToken",
    "VerificationTokenProvider",
]
