"""Lexicography application contracts: manually selected lexemes (BH-54)."""

from cadmus.lexicography.application import (
    CreateLexemeService,
    DeleteLexemeService,
    FinishScanningService,
    LexemeInput,
    LexemeQueryService,
    PageProgress,
    ScanProgress,
    ScanProgressService,
    UpdateLexemeInput,
    UpdateLexemeService,
)
from cadmus.lexicography.domain import (
    DUPLICATE_OVERLAP_RATIO,
    MAX_SOURCE_TEXT_LENGTH,
    DictionaryNotReadyToScanError,
    DuplicateLexemeError,
    Lexeme,
    LexemeAccessError,
    LexemeEvent,
    LexemeEventType,
    LexemeNotFoundError,
    LexemeOrigin,
    LexemePageNotFoundError,
    LexemeValidationError,
    changed_lexeme_fields,
    find_overlapping_lexeme,
    validate_lexeme_fields,
)
from cadmus.lexicography.ports import (
    LexicographyRepository,
    LexicographyUnitOfWork,
    LexicographyUnitOfWorkFactory,
)

__all__ = [
    "DUPLICATE_OVERLAP_RATIO",
    "MAX_SOURCE_TEXT_LENGTH",
    "CreateLexemeService",
    "DeleteLexemeService",
    "DictionaryNotReadyToScanError",
    "DuplicateLexemeError",
    "FinishScanningService",
    "Lexeme",
    "LexemeAccessError",
    "LexemeEvent",
    "LexemeEventType",
    "LexemeInput",
    "LexemeNotFoundError",
    "LexemeOrigin",
    "LexemePageNotFoundError",
    "LexemeQueryService",
    "LexemeValidationError",
    "LexicographyRepository",
    "LexicographyUnitOfWork",
    "LexicographyUnitOfWorkFactory",
    "PageProgress",
    "ScanProgress",
    "ScanProgressService",
    "UpdateLexemeInput",
    "UpdateLexemeService",
    "changed_lexeme_fields",
    "find_overlapping_lexeme",
    "validate_lexeme_fields",
]
