/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a one-time password reset link */
        post: operations["forgot_password_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an authenticated browser session */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate the current authenticated browser session */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a pending user account */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with a one-time reset token */
        post: operations["reset_password_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve the current authenticated browser session */
        get: operations["current_session_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate an account with a one-time email token */
        post: operations["verify_email_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a dictionary source PDF and create its draft */
        post: operations["upload_dictionaries_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionaries/{dictionary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a dictionary draft and its readiness gaps */
        get: operations["get_dictionary_dictionaries__dictionary_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Save bibliographic, language, and legal metadata for a draft */
        patch: operations["save_metadata_dictionaries__dictionary_id__patch"];
        trace?: never;
    };
    "/dictionaries/{dictionary_id}/source/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the immutable original source PDF */
        get: operations["download_source_dictionaries__dictionary_id__source_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API liveness */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue the infrastructure test task */
        post: operations["enqueue_test_task_tasks_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/test/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read test task status and result */
        get: operations["get_test_task_tasks_test__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountStatus
         * @description Lifecycle states currently owned by the identity module.
         * @enum {string}
         */
        AccountStatus: "pending_verification" | "active";
        /**
         * ActivationFailure
         * @description Safe public reasons why account activation failed.
         * @enum {string}
         */
        ActivationFailure: "invalid" | "expired" | "used";
        /**
         * AuthenticatedUserResponse
         * @description Non-sensitive identity details for an authenticated browser.
         */
        AuthenticatedUserResponse: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * AuthenticationErrorResponse
         * @description Safe authentication failure contract.
         */
        AuthenticationErrorResponse: {
            code: components["schemas"]["AuthenticationFailure"];
            /** Message */
            message: string;
        };
        /**
         * AuthenticationFailure
         * @description Safe public reasons why login or session authentication failed.
         * @enum {string}
         */
        AuthenticationFailure: "invalid_credentials" | "unverified_account" | "invalid_session";
        /** Body_upload_dictionaries_upload_post */
        Body_upload_dictionaries_upload_post: {
            /** File */
            file: string;
        };
        /**
         * ContributorRequest
         * @description One ordered contributor entry as submitted by the client.
         */
        ContributorRequest: {
            /** Name */
            name: string;
            role: components["schemas"]["ContributorRole"];
        };
        /**
         * ContributorResponse
         * @description One ordered contributor entry.
         */
        ContributorResponse: {
            /** Name */
            name: string;
            /** Position */
            position: number;
            role: components["schemas"]["ContributorRole"];
        };
        /**
         * ContributorRole
         * @description Supported contributor roles.
         * @enum {string}
         */
        ContributorRole: "author" | "compiler";
        /**
         * DictionaryResponse
         * @description The dictionary draft, its structured metadata, and readiness gaps.
         */
        DictionaryResponse: {
            /** Contributors */
            contributors: components["schemas"]["ContributorResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Dictionary Type */
            dictionary_type: string | null;
            /** Digital Source */
            digital_source: string | null;
            /** Edition */
            edition: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isbn */
            isbn: string | null;
            /** Language Codes */
            language_codes: string[];
            legal_status: components["schemas"]["LegalStatus"] | null;
            /** License Type */
            license_type: string | null;
            /** Missing Required Fields */
            missing_required_fields: string[];
            /** Permission Reference */
            permission_reference: string | null;
            /** Publication Year */
            publication_year: number | null;
            /** Publisher */
            publisher: string | null;
            /** Rights Note */
            rights_note: string | null;
            source?: components["schemas"]["SourceFileResponse"] | null;
            status: components["schemas"]["DictionaryStatus"];
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DictionaryStatus
         * @description Configuration-readiness status owned by this Story (and BH-31).
         * @enum {string}
         */
        DictionaryStatus: "draft" | "configured";
        /**
         * DuplicateSourceResponse
         * @description Structured duplicate-checksum warning; never discloses other users.
         */
        DuplicateSourceResponse: {
            /**
             * Code
             * @default duplicate_source
             */
            code: string;
            /**
             * Dictionary Id
             * Format: uuid
             */
            dictionary_id: string;
            /** Message */
            message: string;
            /** Title */
            title: string | null;
        };
        /**
         * EnqueuedTaskResponse
         * @description Stable response returned after a task is accepted.
         */
        EnqueuedTaskResponse: {
            status: components["schemas"]["TaskStatus"];
            /** Task Id */
            task_id: string;
        };
        /**
         * ErrorResponse
         * @description Stable, non-sensitive error contract for a single failure reason.
         */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * FieldErrorsResponse
         * @description Validation errors addressable by form field.
         */
        FieldErrorsResponse: {
            /** Errors */
            errors: {
                [key: string]: string;
            };
        };
        /**
         * ForgotPasswordRequest
         * @description Bounded password-reset request input carried only in a POST body.
         */
        ForgotPasswordRequest: {
            /** Email */
            email: string;
        };
        /**
         * ForgotPasswordResponse
         * @description Neutral outcome that never discloses whether the email is registered.
         */
        ForgotPasswordResponse: {
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Stable response contract for API liveness.
         */
        HealthResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * InspectionStatus
         * @description Lifecycle of the asynchronous, worker-side PDF structural inspection.
         * @enum {string}
         */
        InspectionStatus: "pending" | "verified" | "failed";
        /**
         * LegalStatus
         * @description Recorded legal status of the digitized source.
         * @enum {string}
         */
        LegalStatus: "public_domain" | "licensed" | "permission_granted" | "restricted" | "unknown";
        /**
         * LoginRequest
         * @description Bounded login input carried only in a POST body.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LogoutResponse
         * @description Non-sensitive idempotent logout outcome.
         */
        LogoutResponse: {
            /** Message */
            message: string;
        };
        /**
         * PasswordResetErrorResponse
         * @description Safe reset-token error contract.
         */
        PasswordResetErrorResponse: {
            code: components["schemas"]["PasswordResetFailure"];
            /** Message */
            message: string;
        };
        /**
         * PasswordResetFailure
         * @description Safe public reasons why a password reset failed.
         * @enum {string}
         */
        PasswordResetFailure: "invalid" | "expired" | "used";
        /**
         * QueueUnavailableResponse
         * @description Stable response when Redis cannot serve queue operations.
         */
        QueueUnavailableResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * RegistrationRequest
         * @description Bounded registration input.
         */
        RegistrationRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Password Confirmation */
            password_confirmation: string;
        };
        /**
         * RegistrationResponse
         * @description Safe account creation response.
         */
        RegistrationResponse: {
            /** Message */
            message: string;
            status: components["schemas"]["AccountStatus"];
        };
        /**
         * ResetPasswordRequest
         * @description Password reset confirmation carried only in a POST body.
         */
        ResetPasswordRequest: {
            /** New Password */
            new_password: string;
            /** New Password Confirmation */
            new_password_confirmation: string;
            /** Token */
            token: string;
        };
        /**
         * ResetPasswordResponse
         * @description Public password reset outcome.
         */
        ResetPasswordResponse: {
            /** Message */
            message: string;
        };
        /**
         * SaveMetadataRequest
         * @description Full BH-27 metadata submission; missing required fields are allowed.
         */
        SaveMetadataRequest: {
            /** Contributors */
            contributors?: components["schemas"]["ContributorRequest"][];
            /** Description */
            description?: string | null;
            /** Dictionary Type */
            dictionary_type?: string | null;
            /** Digital Source */
            digital_source?: string | null;
            /** Edition */
            edition?: string | null;
            /** Isbn */
            isbn?: string | null;
            /** Language Codes */
            language_codes?: string[];
            legal_status?: components["schemas"]["LegalStatus"] | null;
            /** License Type */
            license_type?: string | null;
            /** Permission Reference */
            permission_reference?: string | null;
            /** Publication Year */
            publication_year?: number | null;
            /** Publisher */
            publisher?: string | null;
            /** Rights Note */
            rights_note?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * SourceFileResponse
         * @description Technical facts about the uploaded PDF and its inspection state.
         */
        SourceFileResponse: {
            /** Byte Size */
            byte_size: number;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** Inspection Error */
            inspection_error?: string | null;
            inspection_status: components["schemas"]["InspectionStatus"];
            /** Mime Type */
            mime_type: string;
            /** Original Filename */
            original_filename: string;
            /** Page Count */
            page_count: number | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /**
         * TaskStatus
         * @description Transport-neutral task states exposed to API clients.
         * @enum {string}
         */
        TaskStatus: "queued" | "running" | "succeeded" | "failed";
        /**
         * TaskStatusResponse
         * @description Stable response for task progress and result polling.
         */
        TaskStatusResponse: {
            /** Error */
            error?: string | null;
            /** Result */
            result?: {
                [key: string]: string;
            } | null;
            status: components["schemas"]["TaskStatus"];
            /** Task Id */
            task_id: string;
        };
        /**
         * TestTaskRequest
         * @description Bounded input for the deterministic test task.
         */
        TestTaskRequest: {
            /** Value */
            value: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationErrorResponse
         * @description Safe token error contract.
         */
        VerificationErrorResponse: {
            code: components["schemas"]["ActivationFailure"];
            /** Message */
            message: string;
        };
        /**
         * VerificationRequest
         * @description Verification token supplied in a body so access logs cannot capture it.
         */
        VerificationRequest: {
            /** Token */
            token: string;
        };
        /**
         * VerificationResponse
         * @description Public activation outcome.
         */
        VerificationResponse: {
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forgot_password_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description The email or password is incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationErrorResponse"];
                };
            };
            /** @description The account has not been verified */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cadmus_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponse"];
                };
            };
            /** @description The normalized email is already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorsResponse"];
                };
            };
            /** @description Registration fields are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorsResponse"];
                };
            };
        };
    };
    reset_password_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
            /** @description The reset token is invalid, expired, or used */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetErrorResponse"];
                };
            };
            /** @description The new password is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorsResponse"];
                };
            };
        };
    };
    current_session_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cadmus_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description The browser has no valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
            /** @description The verification token is invalid, expired, or used */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dictionaries_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cadmus_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dictionaries_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryResponse"];
                };
            };
            /** @description The browser has no valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A source with this checksum already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateSourceResponse"];
                };
            };
            /** @description The upload exceeds the configured maximum size */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The file failed type or signature validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorsResponse"];
                };
            };
        };
    };
    get_dictionary_dictionaries__dictionary_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dictionary_id: string;
            };
            cookie?: {
                cadmus_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryResponse"];
                };
            };
            /** @description The browser has no valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The dictionary does not exist or is not owned by the caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_metadata_dictionaries__dictionary_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dictionary_id: string;
            };
            cookie?: {
                cadmus_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveMetadataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryResponse"];
                };
            };
            /** @description The browser has no valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The dictionary does not exist or is not owned by the caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metadata fields are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorsResponse"];
                };
            };
        };
    };
    download_source_dictionaries__dictionary_id__source_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dictionary_id: string;
            };
            cookie?: {
                cadmus_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description The browser has no valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The dictionary does not exist or is not owned by the caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    enqueue_test_task_tasks_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueuedTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The Redis task queue is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueUnavailableResponse"];
                };
            };
        };
    };
    get_test_task_tasks_test__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The Redis task queue is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueUnavailableResponse"];
                };
            };
        };
    };
}
